// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Vitality.Website.IntegrationTests.Features.Presales
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CardsTabbedFeature : Xunit.IClassFixture<CardsTabbedFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CardsTabbed.feature"
#line hidden
        
        public CardsTabbedFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CardsTabbed", "\tIn order to avoid silly mistakes\r\n\tAs a Cards Tabbed user\r\n\tI want to be able to" +
                    " check cards tabbed works", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(CardsTabbedFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Check cards tabbed in full screen view")]
        [Xunit.TraitAttribute("FeatureTitle", "CardsTabbed")]
        [Xunit.TraitAttribute("Description", "Check cards tabbed in full screen view")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Cardstabbed")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckCardsTabbedInFullScreenView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check cards tabbed in full screen view", new string[] {
                        "Presales",
                        "Cardstabbed",
                        "SIT"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I am on presales /dev/cards-tabbed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.When("I resize to full-screen view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("I expect the correct CSS cards tabbed values to appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
 testRunner.And("I expect the cards tabbed partner Cineworld Vue to be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Check cards tabbed in mobile view")]
        [Xunit.TraitAttribute("FeatureTitle", "CardsTabbed")]
        [Xunit.TraitAttribute("Description", "Check cards tabbed in mobile view")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Cardstabbed")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckCardsTabbedInMobileView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check cards tabbed in mobile view", new string[] {
                        "Presales",
                        "Cardstabbed",
                        "SIT"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("I am on presales /dev/cards-tabbed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 17
 testRunner.When("I resize to mobile view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.Then("I expect the correct CSS cards tabbed values to appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.And("I expect the cards tabbed partner Cineworld Vue to be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Check cards tabbed navigation menu searches for partner")]
        [Xunit.TraitAttribute("FeatureTitle", "CardsTabbed")]
        [Xunit.TraitAttribute("Description", "Check cards tabbed navigation menu searches for partner")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Cardstabbed")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckCardsTabbedNavigationMenuSearchesForPartner()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check cards tabbed navigation menu searches for partner", new string[] {
                        "Presales",
                        "Cardstabbed",
                        "SIT"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("I am on presales /dev/cards-tabbed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
 testRunner.And("I resize to mobile view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.When("I click on cards tabbed navigation menu Active Rewards", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 26
 testRunner.Then("I expect the cards tabbed partner Starbucks to be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Check cards tabbed call to action button works")]
        [Xunit.TraitAttribute("FeatureTitle", "CardsTabbed")]
        [Xunit.TraitAttribute("Description", "Check cards tabbed call to action button works")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Cardstabbed")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckCardsTabbedCallToActionButtonWorks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check cards tabbed call to action button works", new string[] {
                        "Presales",
                        "Cardstabbed",
                        "SIT"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("I am on presales /dev/cards-tabbed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 31
 testRunner.When("I click on cards tabbed navigation menu Active Rewards", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.And("I click on the cards tabbed Starbucks partner Explore Starbucks button link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.Then("I expect the presales /rewards/partners/active-rewards/starbucks/ to open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CardsTabbedFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CardsTabbedFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
