// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Vitality.Website.IntegrationTests.Features.Presales
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RedirectsFeature : Xunit.IClassFixture<RedirectsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Redirects.feature"
#line hidden
        
        public RedirectsFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Redirects", "\tIn order validate redirects correctly work\r\n\tAs a redirect user\r\n\tI want to be r" +
                    "edirected to a different page", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(RedirectsFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Check redirects (cricket) works on Presales")]
        [Xunit.TraitAttribute("FeatureTitle", "Redirects")]
        [Xunit.TraitAttribute("Description", "Check redirects (cricket) works on Presales")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Redirects")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckRedirectsCricketWorksOnPresales()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check redirects (cricket) works on Presales", new string[] {
                        "Presales",
                        "Redirects",
                        "SIT"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I am on presales /cricket/", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
    testRunner.Then("I expect the presales /community/sponsorship/ to open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Check redirects (youtube) works on Presales")]
        [Xunit.TraitAttribute("FeatureTitle", "Redirects")]
        [Xunit.TraitAttribute("Description", "Check redirects (youtube) works on Presales")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Redirects")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckRedirectsYoutubeWorksOnPresales()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check redirects (youtube) works on Presales", new string[] {
                        "Presales",
                        "Redirects",
                        "SIT"});
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("I am on presales /usingmemberzone/", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
 testRunner.Then("I see the webpage https://www.youtube.com/watch?v=MaS5qoh8AUQ&feature=youtu.be", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Check redirects (fitbug) works on Advisers")]
        [Xunit.TraitAttribute("FeatureTitle", "Redirects")]
        [Xunit.TraitAttribute("Description", "Check redirects (fitbug) works on Advisers")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Redirects")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckRedirectsFitbugWorksOnAdvisers()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check redirects (fitbug) works on Advisers", new string[] {
                        "Presales",
                        "Redirects",
                        "SIT"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("I am on advisers /rewards/partners/activity-tracking/fitbug/", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
    testRunner.Then("I expect the advisers /rewards/partners/activity-tracking/ to open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Check page not found works on Presales")]
        [Xunit.TraitAttribute("FeatureTitle", "Redirects")]
        [Xunit.TraitAttribute("Description", "Check page not found works on Presales")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Redirects")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckPageNotFoundWorksOnPresales()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check page not found works on Presales", new string[] {
                        "Presales",
                        "Redirects",
                        "SIT"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("I am on presales /unknownpage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
    testRunner.Then("I expect the page Not found to appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Check page not found works on Advisers")]
        [Xunit.TraitAttribute("FeatureTitle", "Redirects")]
        [Xunit.TraitAttribute("Description", "Check page not found works on Advisers")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Redirects")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckPageNotFoundWorksOnAdvisers()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check page not found works on Advisers", new string[] {
                        "Presales",
                        "Redirects",
                        "SIT"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("I am on advisers /unknownpage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 29
    testRunner.Then("I expect the page Not found to appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                RedirectsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                RedirectsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
