// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Vitality.Website.IntegrationTests.Features.Presales
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SummaryComponentFeature : Xunit.IClassFixture<SummaryComponentFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SummaryComponent.feature"
#line hidden
        
        public SummaryComponentFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SummaryComponent", "\tIn order to avoid silly mistakes\r\n\tAs a Summary Component user\r\n\tI want to be ab" +
                    "le to view the Summary Component", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(SummaryComponentFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Check Summary Component displays in full view")]
        [Xunit.TraitAttribute("FeatureTitle", "SummaryComponent")]
        [Xunit.TraitAttribute("Description", "Check Summary Component displays in full view")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Summarycomponent")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckSummaryComponentDisplaysInFullView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Summary Component displays in full view", new string[] {
                        "Presales",
                        "Summarycomponent",
                        "SIT"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I am on presales /dev/summary-component", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.When("I resize to full-screen view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("I expect the correct CSS summary component values to appear in full view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Check Summary Component displays in mobile view")]
        [Xunit.TraitAttribute("FeatureTitle", "SummaryComponent")]
        [Xunit.TraitAttribute("Description", "Check Summary Component displays in mobile view")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Summarycomponent")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckSummaryComponentDisplaysInMobileView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Summary Component displays in mobile view", new string[] {
                        "Presales",
                        "Summarycomponent",
                        "SIT"});
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("I am on presales /dev/summary-component", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.When("I resize to mobile view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
 testRunner.Then("I expect the correct CSS summary component values to appear in full view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Check Summary Component button works")]
        [Xunit.TraitAttribute("FeatureTitle", "SummaryComponent")]
        [Xunit.TraitAttribute("Description", "Check Summary Component button works")]
        [Xunit.TraitAttribute("Category", "Presales")]
        [Xunit.TraitAttribute("Category", "Summarycomponent")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void CheckSummaryComponentButtonWorks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Summary Component button works", new string[] {
                        "Presales",
                        "Summarycomponent",
                        "SIT"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line 21
 testRunner.Given("I am on presales /dev/summary-component", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
 testRunner.When("I click on the summary component button Cheesecake", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.Then("I expect the presales / to open", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SummaryComponentFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SummaryComponentFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
