// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Vitality.Website.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class LiteratureLibraryFeature : Xunit.IClassFixture<LiteratureLibraryFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "LiteratureLibrary.feature"
#line hidden
        
        public LiteratureLibraryFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "LiteratureLibrary", "\tIn order to download a sales literature document\r\n\tAs an advisers user\r\n\tI want " +
                    "to be able to download sales literature documents", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(LiteratureLibraryFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.TheoryAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "LiteratureLibrary")]
        [Xunit.TraitAttribute("Description", "Sales Literature - Searching")]
        [Xunit.TraitAttribute("Category", "SIT")]
        [Xunit.InlineDataAttribute("/dev/sales-library", "Business healthcare aid", new string[0])]
        public virtual void SalesLiterature_Searching(string initialpage, string literatureType, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SIT"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sales Literature - Searching", @__tags);
#line 8
 this.ScenarioSetup(scenarioInfo);
#line 9
    testRunner.Given(string.Format("I am on the {0}", initialpage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
    testRunner.When(string.Format("I search for {0} document", literatureType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then(string.Format("I expect the {0} document to be visible", literatureType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
 testRunner.And("I expect the download and email  buttons to be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.TheoryAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "LiteratureLibrary")]
        [Xunit.TraitAttribute("Description", "Sales Literature - Choosing")]
        [Xunit.TraitAttribute("Category", "SIT")]
        [Xunit.InlineDataAttribute("/dev/sales-library", "Business and Corporate", "Business healthcare aid", new string[0])]
        public virtual void SalesLiterature_Choosing(string initialpage, string literatureType, string availableLiterature, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SIT"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sales Literature - Choosing", @__tags);
#line 20
 this.ScenarioSetup(scenarioInfo);
#line 21
    testRunner.Given(string.Format("I am on the {0}", initialpage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
    testRunner.When(string.Format("I choose Literature Type {0}", literatureType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.And(string.Format("I select on {0} Literature", availableLiterature), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.Then(string.Format("I expect the {0} document to be visible", availableLiterature), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 25
 testRunner.And("I expect the download and email  buttons to be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.TheoryAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "LiteratureLibrary")]
        [Xunit.TraitAttribute("Description", "Member Literature - Searching")]
        [Xunit.TraitAttribute("Category", "SIT")]
        [Xunit.InlineDataAttribute("/dev/member-library", "01", "12", "2016", "Business healthcare aid", new string[0])]
        public virtual void MemberLiterature_Searching(string initialpage, string dD, string mM, string yYYY, string availableLiterature, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SIT"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Member Literature - Searching", @__tags);
#line 34
 this.ScenarioSetup(scenarioInfo);
#line 35
 testRunner.Given(string.Format("I am on the {0}", initialpage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 36
 testRunner.And(string.Format("I enter plan start date {0} {1} {2}", dD, mM, yYYY), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.When("click on the submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.And(string.Format("I select on {0} Literature", availableLiterature), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.Then(string.Format("I expect the {0} document to be visible", availableLiterature), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 40
 testRunner.And("I expect the download and email  buttons to be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.TheoryAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "LiteratureLibrary")]
        [Xunit.TraitAttribute("Description", "Member Literature - Choosing")]
        [Xunit.TraitAttribute("Category", "SIT")]
        [Xunit.InlineDataAttribute("/dev/member-library", "Business and Corporate", "Business healthcare aid", new string[0])]
        public virtual void MemberLiterature_Choosing(string initialpage, string literatureType, string availableLiterature, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SIT"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Member Literature - Choosing", @__tags);
#line 47
 this.ScenarioSetup(scenarioInfo);
#line 48
    testRunner.Given(string.Format("I am on the {0}", initialpage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 49
    testRunner.When(string.Format("I choose Literature Type {0}", literatureType), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.And(string.Format("I select on {0} Literature", availableLiterature), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.Then(string.Format("I expect the {0} document to be visible", availableLiterature), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 52
 testRunner.And("I expect the download and email  buttons to be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                LiteratureLibraryFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                LiteratureLibraryFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
