// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Vitality.Website.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class WFFMFeature : Xunit.IClassFixture<WFFMFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "WFFM.feature"
#line hidden
        
        public WFFMFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "WFFM", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(WFFMFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.TheoryAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "WFFM")]
        [Xunit.TraitAttribute("Description", "Submit Valid Web Form")]
        [Xunit.TraitAttribute("Category", "SIT")]
        [Xunit.InlineDataAttribute("Matt", "Le Tissier", "Other", "Test@Test.com", "02380999999", "1", "May", "2016", "Magic", "Yes", new string[0])]
        public virtual void SubmitValidWebForm(string firstName, string lastName, string otherName, string email, string phone, string day, string mM, string yYYY, string dropList, string checkBox, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SIT"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Submit Valid Web Form", @__tags);
#line 7
 this.ScenarioSetup(scenarioInfo);
#line 8
    testRunner.Given("I am on advisers /dev/wffm", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
    testRunner.When(string.Format("I enter the form details {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}", firstName, lastName, otherName, email, phone, day, mM, yYYY, dropList, checkBox), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.And("I click on the Submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.Then("I expect the web forms \'Thank you for filling in the form!\' message to appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.TheoryAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "WFFM")]
        [Xunit.TraitAttribute("Description", "Submit Invalid Web Form")]
        [Xunit.TraitAttribute("Category", "SIT")]
        [Xunit.InlineDataAttribute("Matt", "LeTissier", "Other", "IncorrectEmail", "02380999999", "1", "May", "2016", "Magic", "Yes", new string[0])]
        [Xunit.InlineDataAttribute("Matt", "LeTissier", "Other", "Test@Test.com", "IncorrectPhone", "1", "May", "2016", "Magic", "Yes", new string[0])]
        [Xunit.InlineDataAttribute("", "LeTissier", "Other", "Test@Test.com", "02380999999", "1", "May", "2016", "Magic", "Yes", new string[0])]
        public virtual void SubmitInvalidWebForm(string firstName, string lastName, string otherName, string email, string phone, string day, string mM, string yYYY, string dropList, string checkBox, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "SIT"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Submit Invalid Web Form", @__tags);
#line 19
 this.ScenarioSetup(scenarioInfo);
#line 20
    testRunner.Given("I am on advisers /dev/wffm", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
    testRunner.When(string.Format("I enter the form details {0} {1} {2} {3} {4} {5} {6} {7} {8} {9}", firstName, lastName, otherName, email, phone, day, mM, yYYY, dropList, checkBox), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.And("I click on the Submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.Then("I expect the web forms mandatory error message to appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                WFFMFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                WFFMFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
