// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Vitality.Website.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class WFFMFeature : Xunit.IClassFixture<WFFMFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "WFFM.feature"
#line hidden
        
        public WFFMFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "WFFM", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(WFFMFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Submit Valid Web Form")]
        [Xunit.TraitAttribute("FeatureTitle", "WFFM")]
        [Xunit.TraitAttribute("Description", "Submit Valid Web Form")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void SubmitValidWebForm()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Submit Valid Web Form", new string[] {
                        "SIT"});
#line 8
 this.ScenarioSetup(scenarioInfo);
#line 9
    testRunner.Given("I am on presales /dev/wffm", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("I have entered web forms section 0 and field 0 text box Matt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("I have entered web forms section 0 and field 1 text box LeTissier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("I have entered web forms section 0 and field 2 text box Other Names", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("I have entered web forms section 0 and field 3 text box Test@Test.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("I have entered web forms section 0 and field 4 text box 02380999999", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("I have entered web forms section 0 and field 5 date field 1 January 2016", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("I have entered web forms section 1 and field 0 dropdown list Magic", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("I have entered web forms section 1 and field 1 check box Yes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.When("I click on webform Submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.Then("I expect the web forms Thank you for filling in the form! message to appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Invalid Web Form - Email address")]
        [Xunit.TraitAttribute("FeatureTitle", "WFFM")]
        [Xunit.TraitAttribute("Description", "Invalid Web Form - Email address")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void InvalidWebForm_EmailAddress()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid Web Form - Email address", new string[] {
                        "SIT"});
#line 22
 this.ScenarioSetup(scenarioInfo);
#line 23
    testRunner.Given("I am on presales /dev/wffm", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
 testRunner.And("I have entered web forms section 0 and field 0 text box Matt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("I have entered web forms section 0 and field 1 text box LeTissier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("I have entered web forms section 0 and field 2 text box Other Names", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("I have entered web forms section 0 and field 3 text box IncorrectEmail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("I have entered web forms section 0 and field 4 text box 02380999999", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("I have entered web forms section 0 and field 5 date field 1 January 2016", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("I have entered web forms section 1 and field 0 dropdown list Magic", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("I have entered web forms section 1 and field 1 check box Yes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.When("I click on webform Submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
 testRunner.Then("I expect the web forms The Email Address field contains an invalid email address." +
                    " message to appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Invalid Web Form - Phone number")]
        [Xunit.TraitAttribute("FeatureTitle", "WFFM")]
        [Xunit.TraitAttribute("Description", "Invalid Web Form - Phone number")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void InvalidWebForm_PhoneNumber()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid Web Form - Phone number", new string[] {
                        "SIT"});
#line 36
 this.ScenarioSetup(scenarioInfo);
#line 37
    testRunner.Given("I am on presales /dev/wffm", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 38
 testRunner.And("I have entered web forms section 0 and field 0 text box Matt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And("I have entered web forms section 0 and field 1 text box LeTissier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("I have entered web forms section 0 and field 2 text box Other Names", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("I have entered web forms section 0 and field 3 text box Test@Test.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.And("I have entered web forms section 0 and field 4 text box IncorrectPhone", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.And("I have entered web forms section 0 and field 5 date field 1 January 2016", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.And("I have entered web forms section 1 and field 0 dropdown list Magic", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.And("I have entered web forms section 1 and field 1 check box Yes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.When("I click on webform Submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
 testRunner.Then("I expect the web forms The value of the Phone number field is not valid. message " +
                    "to appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Invalid Web Form - First name")]
        [Xunit.TraitAttribute("FeatureTitle", "WFFM")]
        [Xunit.TraitAttribute("Description", "Invalid Web Form - First name")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void InvalidWebForm_FirstName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid Web Form - First name", new string[] {
                        "SIT"});
#line 50
 this.ScenarioSetup(scenarioInfo);
#line 51
    testRunner.Given("I am on presales /dev/wffm", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 52
 testRunner.And("I have entered web forms section 0 and field 1 text box LeTissier", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.And("I have entered web forms section 0 and field 2 text box Other Names", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.And("I have entered web forms section 0 and field 3 text box Test@Test.com", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.And("I have entered web forms section 0 and field 4 text box 02380999999", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("I have entered web forms section 0 and field 5 date field 1 January 2016", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And("I have entered web forms section 1 and field 0 dropdown list Magic", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And("I have entered web forms section 1 and field 1 check box Yes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.When("I click on webform Submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 60
 testRunner.Then("I expect the web forms The First name field is required. message to appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Web Form single line tool tips - Presales")]
        [Xunit.TraitAttribute("FeatureTitle", "WFFM")]
        [Xunit.TraitAttribute("Description", "Web Form single line tool tips - Presales")]
        [Xunit.TraitAttribute("Category", "SIT")]
        public virtual void WebFormSingleLineToolTips_Presales()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Web Form single line tool tips - Presales", new string[] {
                        "SIT"});
#line 63
 this.ScenarioSetup(scenarioInfo);
#line 64
    testRunner.Given("I am on presales /dev/wffm", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 65
 testRunner.And("I have entered web forms section 0 and field 0 text box Matt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.When("I click on field First name tool tips", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 67
 testRunner.Then("I expect Enter First Name tool tips to be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Web Form Date tool tips - Presales", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "WFFM")]
        [Xunit.TraitAttribute("Description", "Web Form Date tool tips - Presales")]
        public virtual void WebFormDateToolTips_Presales()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Web Form Date tool tips - Presales", new string[] {
                        "ignore"});
#line 70
 this.ScenarioSetup(scenarioInfo);
#line 71
    testRunner.Given("I am on presales /dev/wffm", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 72
 testRunner.And("I have entered web forms section 0 and field 5 date field 1 January 2016", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 73
 testRunner.When("I click on field Submission Date tool tips", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
 testRunner.Then("I expect Enter Submission Date tool tips to be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Web Form Phone Number tool tips - Advisers", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "WFFM")]
        [Xunit.TraitAttribute("Description", "Web Form Phone Number tool tips - Advisers")]
        public virtual void WebFormPhoneNumberToolTips_Advisers()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Web Form Phone Number tool tips - Advisers", new string[] {
                        "ignore"});
#line 77
 this.ScenarioSetup(scenarioInfo);
#line 78
    testRunner.Given("I am on advisers /dev/wffm", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 79
 testRunner.And("I have entered web forms section 0 and field 4 text box 02380999999", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.When("I click on field Phone number tool tips", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
 testRunner.Then("I expect Enter Phone Number tool tips to be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Web Form Date Check box - Advisers", Skip="Ignored")]
        [Xunit.TraitAttribute("FeatureTitle", "WFFM")]
        [Xunit.TraitAttribute("Description", "Web Form Date Check box - Advisers")]
        public virtual void WebFormDateCheckBox_Advisers()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Web Form Date Check box - Advisers", new string[] {
                        "ignore"});
#line 84
 this.ScenarioSetup(scenarioInfo);
#line 85
    testRunner.Given("I am on advisers /dev/wffm", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 86
 testRunner.And("I have entered web forms section 1 and field 0 dropdown list Magic", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.When("I click on field How did you find us? tool tips", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
 testRunner.Then("I expect Select How To Find Us tool tips to be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                WFFMFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                WFFMFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
